CREATE DATABASE IF NOT EXISTS MATHBLOG;

USE MATHBLOG;

CREATE TABLE IF NOT EXISTS USER_TABLE(
    ID_USER INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(25),
    EMAIL VARCHAR(60),
    PASSWORD VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS POST();

CREATE TABLE IF NOT EXISTS CATEGORY();